cache:
  paths:
before_script:
  - "cd /home/gitlab-runner/sqream-with-submodules/sqream"
  - "git checkout develop"
  - "git pull"
  - "make -j7 all"
  - "killall -9 sqreamd metadata_server || echo 'Sqream wan not running.'"
  - "./build/metadata_server &"
  - "./build/sqreamd &"
  - "cd /home/gitlab-runner/jdbc-driver"
  - "git fetch"
  - "git checkout $CI_COMMIT_REF_NAME"
  - "git status"
  - "git log"
tests_and_benchmark:
  script:
    - "mvn clean package"
  only:
    refs:
      - merge_requests
      - master
      - web