cache:
  paths:
before_script:
  - "cd /home/gitlab-runner/sqream-with-submodules/sqream"
  - "git checkout develop"
  - "git pull"
  - "make -j7 all"
  - "killall -q metadata_server sqreamd"
  - "./build/metadata_server &"
  - "./build/sqreamd &"
  - "cd /home/gitlab-runner/jdbc-driver;"
tests_and_benchmark:
  script:
    - "mvn clean package"
  only:
    refs:
      - merge_requests
      - master
      - web