cache:
  paths:
before_script:
  - "mvn clean"
  - "mvn package -DskipTests"
  - "rm -rf /home/gitlab-runner/sqream-with-submodules/jdbc-driver/target"
  - "ls -lthr target"
  - "cp target/sqream-jdbc-3.1-jar-with-dependencies.jar target/sqream-jdbc-with-dependencies.jar"
  - "mkdir  /home/gitlab-runner/sqream-with-submodules/jdbc-driver/target"  
  - "ln -s target/sqream-jdbc-with-dependencies.jar /home/gitlab-runner/sqream-with-submodules/jdbc-driver/target/sqream-jdbc-with-dependencies.jar"
  - "ln -s target /home/gitlab-runner/sqream-with-submodules/jdbc-driver/target"
  - "ls -lthr target"    
  - "cd /home/gitlab-runner/sqream-with-submodules/sqream"
  - "git checkout develop"
  - "#make clean"
  - "#make -j7 all |& tee /home/gitlab-runner/build_logs/${CI_COMMIT_REF_NAME}.log"
tests_and_benchmark:
  script:
    - "#rm -rf /home/gitlab-runner/sqream_testing_temp" # So we can test different storage versions
    - "python tests/developer_regression_query.py -m replace.sql-00 --sqream.save-style=jdbc --suite.timeout=2400"
  only:
    refs:
      - merge_requests
      - master
      - web

