cache:
  paths:
before_script:
  - "mvn clean"
  - "mvn package -DskipTests"
  - "ln -s target /home/gitlab-runner/sqream-with-submodules/jdbc-driver/target"
  - "cd /home/gitlab-runner/sqream-with-submodules/sqream"
  - "git checkout develop"
  - "#make clean"
  - "#make -j7 all |& tee /home/gitlab-runner/build_logs/${CI_COMMIT_REF_NAME}.log"
tests_and_benchmark:
  script:
    - "#rm -rf /home/gitlab-runner/sqream_testing_temp" # So we can test different storage versions
    - "#python tests/developer_regression.py --sqream.save-style=jdbc --suite.timeout=2400"
    - "python tests/cvidya.py --sqream.save-style=jdbc --suite.timeout=2400"
  only:
    refs:
      - merge_requests
      - master
      - web

