cache:
  paths:
before_script:
  - "mvn clean"
  - "mvn package -DskipTests"
  - "echo `pwd`"
  - "cp -r /home/sqream/jdbc-driver/target /home/sqream/sqream-with-submodules/jdbc-driver/"
  - "cd /home/sqream/sqream-with-submodules/sqream"
  - "git checkout develop"
  - "make clean"
  - "make -j7 all |& tee /home/gitlabrunner/build_logs/${CI_COMMIT_REF_NAME}.log |& MakeFilters ; ( exit ${PIPESTATUS[0]} )"
tests_and_benchmark:
  script:
    - "rm -rf /home/sqream/sqream_testing_temp" # So we can test different storage versions
    - "python tests/developer_regression.py --sqream.save-style=jdbc --suite.timeout=2400"
  only:
    refs:
      - merge_requests
      - master
      - web
